config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#landing"

  #pages
  get "home", to: 'pages#home', as: :home
  get "about", to: 'pages#about', as: :about
  get "contact", to: 'pages#contact', as: :contact
  get "terrain", to: 'pages#terrain', as: :terrain



  resources :programming_projects
  # get "programming_projects", to: 'programming_projects#index'
  # get "programming_projects/:id", to: 'programming_projects#show'


  resources :animation_projects
  # get "animation_projects", to: 'animation_projects#index'
  # get "animation_projects/:id", to: 'animation_projects#show'

end

app/models/animation_project.rb
class AnimationProject < ApplicationRecord
  has_one_attached :cover_photo
  has_many_attached :photos
  has_many_attached :videos

  has_rich_text :rich_description

  validates :cover_photo, presence: true

  # Virtual attribute for removing the cover photo
  attr_accessor :remove_cover_photo

  # Callback to check for the cover photo removal
  before_save :check_remove_cover_photo

  private

  def check_remove_cover_photo
    cover_photo.purge if remove_cover_photo == '1'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/programming_project.rb
class ProgrammingProject < ApplicationRecord
  has_one_attached :cover_photo
  has_many_attached :photos

  has_rich_text :rich_description

  validates :cover_photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Add a method in the User model
  def is_admin?
    self.email == 'malin@byemalin.com'  # Replace with your admin email
  end

end

app/controllers/animation_projects_controller.rb
class AnimationProjectsController < ApplicationController

  before_action :set_animation_project, only: [:edit, :update]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:new, :create, :edit, :update]  # for user-specific access control



  def index
    @animation_projects = AnimationProject.all
  end

  def show
    @project = AnimationProject.find(params[:id])
  end

  def new
    @animation_project = AnimationProject.new
  end

  def create
    @animation_project = AnimationProject.new(animation_project_params)
    if @animation_project.save
      redirect_to animation_projects_path, notice: 'Animation project was successfully created.'
    else
      render :new
    end
  end

  def edit
    # The 'set_animation_project' before_action loads the project to edit
  end



  def update
    # Handle cover photo deletion
    if params[:animation_project][:remove_cover_photo] == '1'
      @animation_project.cover_photo.purge
    end

    # Handle additional photos deletion
    if params[:animation_project][:remove_photos].present?
      removable_ids = params[:animation_project][:remove_photos].map(&:to_i)
      @animation_project.photos.each do |photo|
        photo.purge if removable_ids.include?(photo.id)
      end
    end

    if @animation_project.update(animation_project_params)
      redirect_to animation_projects_path, notice: 'Animation project was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_animation_project
    @animation_project = AnimationProject.find(params[:id])
  end


  def animation_project_params
    params.require(:animation_project).permit(
      :title, :sub_heading, :description, :video_url,
      :remove_cover_photo, # Ensure this is a single symbol
      :cover_photo,
      :tiktok_id,
      :rich_description,
      videos: [], # Using colon notation directly for arrays
      tags: [],
      photos: [],
      remove_photos: [], # Using colon notation for hashes
      remove_videos: []  # No comma needed after the last item
    )
  end




  def check_user
    # Ensure only the allowed user can edit and update the project
    redirect_to root_path, alert: "Unauthorized access!" unless current_user && current_user.is_admin?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  # before_action :authenticate_user!, only: [:dashboard, :profile]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:about, :landing, :contact, :home]
  # before_action :authenticate_user!, only: [:dashboard, :profile]
  before_action :authenticate_user!, only: [:terrain]
end

app/controllers/programming_projects_controller.rb
class ProgrammingProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:new, :create, :edit, :update]

  def index
    @programming_projects = ProgrammingProject.all
    @programming_projects = @programming_projects.order(created_at: :desc)

  end

  def show
    @project = ProgrammingProject.find(params[:id])
  end

  def new
    @programming_project = ProgrammingProject.new
  end

  def create
    @programming_project = ProgrammingProject.new(programming_project_params)
    if @programming_project.save
      redirect_to programming_projects_path, notice: 'Project was successfully created.'
    else
      render :new
    end
  end


  before_action :set_programming_project, only: [:edit, :update]

  def edit
  end

  def update
    if params[:programming_project][:remove_cover_photo] == '1'
      @programming_project.cover_photo.purge
    end

    if params[:programming_project][:remove_photos]
      params[:programming_project][:remove_photos].each do |photo_id|
        photo = @programming_project.photos.find(photo_id)
        photo.purge
      end
    end

    if @programming_project.update(programming_project_params)
      redirect_to programming_projects_path, notice: 'Programming project was successfully updated.'
    else
      render :edit
    end
  end

  private

  def check_user
    redirect_to root_path, alert: "Unauthorized access!" unless current_user && current_user.is_admin?
  end

  def set_programming_project
    @programming_project = ProgrammingProject.find(params[:id])
  end

  def programming_project_params
    params.require(:programming_project).permit(:title, :description, :technologies_used, :live_url, :tags, :cover_photo, :rich_description, :active, :tiktok_id, :vimeo_id, photos: [])
  end
end

app/helpers/animation_projects_helper.rb
module AnimationProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programming_projects_helper.rb
module ProgrammingProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/animation_projects/edit.html.erb
<h1>Edit Animation Project</h1>

<%= form_with(model: @animation_project, local: true) do |form| %>
  <%#= render 'form_errors', project: @animation_project %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :sub_heading %>
    <%= form.text_field :sub_heading %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :rich_description, "Detailed Description" %><br>
    <%= form.rich_text_area :rich_description %>
  </div>



  <%# Cover Photo: %>

  <div class="field">
    <%= form.label :cover_photo, "Cover Photo (required)" %>
    <%= form.file_field :cover_photo %>
    <% if @animation_project.cover_photo.attached? %>
      <%= image_tag @animation_project.cover_photo %>
      <div>
        <%= form.check_box :remove_cover_photo %>
        <label>Remove cover photo</label>
      </div>
    <% end %>
  </div>

  <%# Photos: %>

  <div class="field">
    <%= form.label :photos, "Other Photos (optional)" %>
    <%= form.file_field :photos, multiple: true, direct_upload: true %>
    <% @animation_project.photos.each do |photo| %>
      <%= image_tag photo %>
      <%= check_box_tag 'animation_project[remove_photos][]', photo.id %>
      <label>Remove</label>
    <% end %>
  </div>

  <%# Videos: %>

  <div class="field">
    <%= form.label :videos, "Other Videos (optional)" %>
    <%= form.file_field :videos, multiple: true, direct_upload: true %>
    <% @animation_project.videos.each do |video| %>

      <% url = "https://player.cloudinary.com/embed/?cloud_name=dxvi2kqnz&public_id=production/#{video.key}"%>
      <iframe
        src="<%= url %>"
        frameborder="0"
        allow="fullscreen">
      </iframe>

      <%= check_box_tag 'animation_project[remove_videos][]', video.id %>
      <label>Remove</label>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Update Animation Project" %>
  </div>
<% end %>

app/views/animation_projects/index.html.erb
<main class = "mainSection90Width">


  <h3>Motion</h3>

  <p>See more on <a href="https://www.instagram.com/byemalin" target="_blank">Instagram</a></p>
  <br>

  <div class="projectCardsContainer">
    <% @animation_projects.each do |project| %>
      <%= render 'shared/cards/animation_project_card' , project: project%>
    <% end %>
  </div>


</main>

app/views/animation_projects/new.html.erb
<h1>New Animation Project</h1>

<%= form_with model: @animation_project, local: true do |form| %>
  <% if @animation_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animation_project.errors.count, "error") %> prevented this project from being saved:</h2>

      <ul>
      <% @animation_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :sub_heading %>
    <%= form.text_field :sub_heading %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :rich_description, "Detailed Description" %><br>
    <%= form.rich_text_area :rich_description %>
  </div>

  <div class="field">
    <%= form.label :cover_photo, "Cover Photo (required)" %>
    <%= form.file_field :cover_photo, required: true, direct_upload: true %>
  </div>

  <div class="field">
    <%= form.label :videos, "Videos (optional)" %>
    <%= form.file_field :videos, multiple: true, direct_upload: true %>
  </div>

  <div class="field">
    <%= form.label :photos, "Other Photos (optional)" %>
    <%= form.file_field :photos, multiple: true, direct_upload: true %>
  </div>

  <div class="field">
    <%= form.label :tiktok_id %>
    <%= form.text_area :tiktok_id %>
  </div>

  <div class="actions">
    <%= form.submit "Create Project" %>
  </div>
<% end %>

<%= link_to 'Back to List', animation_projects_path %>

app/views/animation_projects/show.html.erb
<main class="animationShow mainSection90Width">

  <%= link_to "< Back", animation_projects_path%>

  <h3><%= @project.title %></h3>
  <p><%= @project.description %></p>







  <div class="videosContainer">
    <% @project.videos.each do |video| %>
      <% url = "https://player.cloudinary.com/embed/?cloud_name=dxvi2kqnz&resource_type=video&public_id=byemalin_portfolio/#{video.key}"%>

      <iframe
        src="<%= url %>"
        frameborder="0"
        allow="fullscreen">
      </iframe>
    <% end %>
  </div>

  <% if @project.rich_description %>
    <div class="rich-description">
      <%= @project.rich_description %>
    </div>
  <% end %>

  <% if current_user&.is_admin? %>
    <%= link_to 'Edit', edit_animation_project_path(@project) %>
  <% end %>


  <% if @project.photos.length > 0 %>
    <p>Additional Photos:</p>

    <div class="additionalPhotos">
      <%@project.photos.each do |photo|%>
      <div class="gridImageContainer">
        <%= cl_image_tag photo.key %>
      </div>
      <% end %>
    </div>

  <% end %>

  <% if false %>
  <#% if @project.tiktok_id %>
    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@byemalin/video/<%= @project.tiktok_id %>" data-video-id="<%= @project.tiktok_id %>" style="height: 580px; max-width: 605px;min-width: 325px;" >
      <section>
        <a target="_blank" title="@byemalin" href="https://www.tiktok.com/@byemalin?refer=embed">@byemalin</a>
      </section>
    </blockquote>
    <script async src="https://www.tiktok.com/embed.js"></script>
  <% end %>


</main>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>byemalin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>


     <% if action_name != "landing" && action_name != "terrain" %>
      <%= javascript_importmap_tags %>
    <% end %>



  </head>

  <body>

    <%= render "shared/flashes" %>

    <% if action_name != "about" %>
      <%= render "shared/navbar" %>
    <% end %>

    <%= render "shared/popup" unless action_name == "home"%>

    <%= yield %>

    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/about.html.erb
<script type="module" src="https://unpkg.com/@splinetool/viewer@1.1.9/build/spline-viewer.js"></script>


<main class="about">

  <section class="hero">
    <%= render "shared/navbar" %>
    <spline-viewer loading-anim-type="spinner-small-light" url="https://prod.spline.design/aeD3wU0OsUgiq4eg/scene.splinecode"></spline-viewer>
  </section>


  <section id = "aboutContent">

    <h3>About</h3>

    <p>Hello, I'm Malin, a versatile programmer and designer based in Paris, originally from Lusaka, Zambia. My journey in tech began at Parsons School of Design, where I earned a BFA in Art, Media, and Technology, deeply exploring the intersection of art and technology. During my studies, I also completed a full-stack Web Development Bootcamp at Le Wagon, where I led projects like a flight-searching app and a clone of Airbnb.</p>
    <br>
    <p>Currently freelancing full-time, I specialise in 3D Product Advertisement and Indie Software Development. My professional portfolio includes a range of projects from animations to frontend solutions, working across sectors like fashion, fintech, and the arts. </p>
    <br>
    <p>I thrive on blending aesthetics with functionality, ensuring every design is not only visually compelling but also highly usable. Whether crafting detailed animations or designing intuitive user interfaces, my goal is to create impactful, resonant experiences.</p>
    <br>
    <p>Always eager to push the envelope and innovate, I actively seek out challenges that sharpen my skills and expand my horizons. If you're looking for a dynamic animator, designer, or developer to bring a fresh perspective to your project, please don't hesitate to reach out!</p>
    <br>

    <h3>Development Skills</h3>
    <div class="skillIcons">
        <img title= "Javascript" alt="Javascript Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg">
        <img title= "HTML" alt="HTML Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-plain-wordmark.svg">
        <img title= "CSS" alt="CSS Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-plain-wordmark.svg">
        <img title= "React" alt="React Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original-wordmark.svg">
        <%# <img title= "Github" alt="Github Icon" src="./assets/img/icons/logos/development/githubLogo.svg"> %>
        <%# <img title= "Git" alt="Git Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-plain-wordmark.svg"> %>
        <%# <img title= "NodeJS" alt="NodeJS Icon" src="./assets/img/icons/logos/development/nodejsLogo.svg"> %>
        <img title= "Ruby" alt="Ruby Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/ruby/ruby-plain-wordmark.svg">
        <img title= "Rails" alt="Rails Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rails/rails-plain-wordmark.svg">

    </div>

    <h3>Proficient Softwares</h3>
    <div class="skillIcons">
        <img title= "Figma" alt="Figma Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg">
        <img title= "Blender" alt="Blender Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/blender/blender-original-wordmark.svg">
        <img title= "Illustrator" alt="Illustrator Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/illustrator/illustrator-plain.svg">
        <img title= "Photoshop" alt="Photoshop Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/photoshop/photoshop-plain.svg">
        <img title= "Premiere Pro" alt="Premiere Pro Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/premierepro/premierepro-plain.svg">
        <img title= "After Effects" alt="After Effects Icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/aftereffects/aftereffects-plain.svg">
        <!-- <img title= "Visual Studio Code" alt="Visual Studio Code Icon" src="./assets/img/icons/logos/softwares/vscodeLogo.svg"> -->
    </div>

    <br>
  </section>
</main>

app/views/pages/contact.html.erb
<main class="contact">
  <section class="splitSection">
      <div class="left">
          <div class="profileImageContainer">
              <img alt="profile picture" src="https://res.cloudinary.com/dxvi2kqnz/image/upload/v1714235462/malin_profile_photo_tjn7qw.jpg">
          </div>

          <address>
              <p class="smallText">Email</p>
              <a href = mailto:"malin@byemalin.com">malin@byemalin.com</a>

              <p class="smallText">Social</p>
              <ul>
                  <li><a href="https://www.linkedin.com/in/malin-mabika/" target="_blank">Linkedin</a></li>
                  <li><a href="https://www.instagram.com/byemalin/" target="_blank">Instagram</a></li>
                  <li><a href="https://github.com/byemalin" target="_blank">Github</a></li>
              </ul>
          </address>
      </div>
      <div class="right">
          <!-- <h2>Let's build together</h2> -->
          <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSemJc_dvOZt3nP2QTK0oA4ZLf_PXNM8JLj6hNwVK6xklZ6hQw/viewform?embedded=true">Loading…</iframe>
      </div>
  </section>
</main>

app/views/pages/home.html.erb
<!--  -->


<section class="hero">
    <div id="heroImageContainer">
        <div class="spacer"></div>
        <!-- Line drawing image for hero:-->
        <img alt='An abstract line drawing' src="https://res.cloudinary.com/dxvi2kqnz/image/upload/v1714049528/lineDrawing_nqjjlg.png">
    </div>


    <!-- POPUP MENU: -->
    <!-- Greeting Container: -->
    <div id="greetingContainer">
        <div id="menuGreeting">
            <h3>&#128075;</h3>
            <h3>Hi I'm Malin</h3>
        </div>
    </div>

    <!-- popup container: -->
    <%= render "shared/popup" %>
</section>



<!-- About Split Section: -->

<section class="splitSection">
    <div class="left">
        <h3>About</h3>

    </div>
    <div class="right">
        <p id="homeAboutBlurb">Hello, I'm Malin, a multi-disciplinary programmer and designer from Lusaka, now creating in Paris.</p>
        <p>Specialising in <strong>Design</strong>, <strong>3D Product Advertisement</strong> and <strong>Indie Software Development</strong>, I blend aesthetics with functionality to craft designs that resonate.</p>
        <%= link_to 'Read more', about_path %>
    </div>
</section>


<!-- Projects Split Section: -->

<section class="splitSection" class="projectsSplitSection">
    <div class="left">
            <h3>Recent Work</h3>
    </div>
    <div class="right" id="recentWork">

        <a href="/programming_projects">
            <div class="recentProject" id="project1">
                <div>
                    <h2>Programming Projects</h2>
                    <p class="smallText">Web Design - Frontend Development - Fullstack Development</p>
                </div>
                <div class="openIcon">
                    <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M1.83007 0.457528V3.11625L12.3612 3.12568L0.88726 14.5997L2.77288 16.4853L14.2469 5.0113L14.2563 15.5425H16.915V0.457528H1.83007Z" fill="#3C3D3E"/>
                    </svg>
                </div>
            </div>
        </a>


        <a href="/animation_projects">
            <div class="recentProject" id="project2">
                <div>
                    <h2>Motion Projects</h2>
                    <p class="smallText">3D Animation - Advertisting - Graphic Design </p>
                </div>
                <div class="openIcon">
                    <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M1.83007 0.457528V3.11625L12.3612 3.12568L0.88726 14.5997L2.77288 16.4853L14.2469 5.0113L14.2563 15.5425H16.915V0.457528H1.83007Z" fill="#3C3D3E"/>
                    </svg>
                </div>
            </div>
        </a>


    </div>
</section>

app/views/pages/landing.html.erb
<!-- Welcome Mat Landing Page -->
<body>
    <main id="landingPageGIFcontainer" >
        <% link_to %>

        <a href="./home">
            <img alt="A GIF of A Welcome Mat" src="https://res.cloudinary.com/dxvi2kqnz/image/upload/v1713537650/welcomeMat_l3dpdx.gif" title="Click to proceed" class="GIF">
        </a>
    </main>
</body>

app/views/programming_projects/index.html.erb
<main class = "mainSection90Width">

  <h3 class = "h3Title90Width">Programming Projects</h3>

  <p>See more on <a href="https://www.github.com/byemalin" target="_blank">Github</a></p>
  <br>

  <div class="projectCardsContainer">
    <% @programming_projects.each do |project| %>

      <%= render 'shared/cards/programming_project_card' , project: project%>

    <% end %>
  </div>



</main>

app/views/programming_projects/show.html.erb
<main class="programmingShow">

  <h3><%= @project.title %></h3>
  <p class="smallText"><%= @project.technologies_used %></p>
  <p><%= @project.description %></p>


  <div class="project-hero">

    <% if @project.live_url && @project.active%>
      <a href="<%= @project.live_url%>" target="_blank">
        <%= cl_image_tag @project.cover_photo.key %>
        <div class="liveUrl">
            <p>Visit Live Site</p>

          <div class="openIcon">
              <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1.83007 0.457528V3.11625L12.3612 3.12568L0.88726 14.5997L2.77288 16.4853L14.2469 5.0113L14.2563 15.5425H16.915V0.457528H1.83007Z" fill="#3C3D3E"/>
              </svg>
          </div>
        </div>
      </a>
    <% else %>
      <%= cl_image_tag @project.cover_photo.key %>
      <div class="liveUrl inactive">
          <p>The live site is currently inactive</p>
          <div class="openIcon">
              <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1.83007 0.457528V3.11625L12.3612 3.12568L0.88726 14.5997L2.77288 16.4853L14.2469 5.0113L14.2563 15.5425H16.915V0.457528H1.83007Z" fill="#3C3D3E"/>
              </svg>
          </div>
      </div>
    <% end %>
  </div>


  <% if @project.vimeo_id != "" %>
    <div>
      <div class="videoWrapper">
        <iframe src="https://player.vimeo.com/video/<%= @project.vimeo_id %>?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow='fullscreen; picture-in-picture; clipboard-write'></iframe>
        <script src="https://player.vimeo.com/api/player.js"></script>
      </div>
    </div>
  <% end %>

  <% if @project.rich_description %>
    <div class="rich-description">
      <%= @project.rich_description %>
    </div>
  <% end %>





  <% if @project.tiktok_id != "" %>
    <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@byemalin/video/<%= @project.tiktok_id %>" data-video-id="<%= @project.tiktok_id %>" style="height: 580px; max-width: 605px;min-width: 325px;" >
      <section>
        <a target="_blank" title="@byemalin" href="https://www.tiktok.com/@byemalin?refer=embed">@byemalin</a>
      </section>
    </blockquote>
    <script async src="https://www.tiktok.com/embed.js"></script>
  <% end %>




  <% if @project.photos.length > 0 %>
  <p>Additional Photos:</p>
    <%@project.photos.each do |photo|%>
      <%= cl_image_tag photo.key %>
    <% end %>
  <% end %>


  <% if current_user&.is_admin? %>
    <%= link_to 'Edit', edit_programming_project_path(@project) %>
  <% end %>


</main>

app/views/shared/_popup.html.erb
<!-- popup container: -->
    <section class="popupMenuContainer">
        <div class="popupMenu">
            <div class="popupContent">
                <nav id="columnNav">
                      <ul>
                        <li><h2><%= link_to "Home", home_path%></h2></li>
                        <li><h2><%= link_to "About", about_path%></h2></li>
                        <li><h2><%= link_to "Contact", contact_path%></h2></li>
                        <li><h2><%= link_to "Animation", animation_projects_path%></h2></li>
                        <li><h2><%= link_to "Code", programming_projects_path%></h2></li>
                      </ul>
                </nav>

                <nav id="popupLinks">
                    <ul>
                        <li><a href="https://www.linkedin.com/in/malin-mabika/" target="_blank">Linkedin</a></li>
                        <li><a href="https://www.instagram.com/byemalin/" target="_blank">Instagram</a></li>
                        <li><a href="https://github.com/byemalin" target="_blank">Github</a></li>
                    </ul>
                </nav>
            </div>

            <div>
                <div class="closeIcon">
                    <svg width="57" height="58" viewBox="0 0 57 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <line x1="13.4345" y1="42.4345" x2="41.7188" y2="14.1502" stroke="#F7F7F7" stroke-width="2"/>
                        <line x1="41.7197" y1="43.8487" x2="13.4354" y2="15.5644" stroke="#F7F7F7" stroke-width="2"/>
                    </svg>
                </div>
            </div>
        </div>
    </section>